<?php

use App\Http\Controllers\AlertController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CraftsmanController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DebtController;
use App\Http\Controllers\InstallmentController;
use App\Http\Controllers\LaborController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\MaterialReturnController;
use App\Http\Controllers\PriceHistoryController;
use App\Http\Controllers\ProjectBandController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\QuoteController;
use App\Http\Controllers\ReceivablesController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\WalletController;
use App\Http\Controllers\WarrantyController;
use App\Http\Controllers\WorkerPaymentController;
use Illuminate\Support\Facades\Route;

// ---- Auth routes (no login required) ----
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

// ---- Redirect root to dashboard ----
Route::get('/', fn () => redirect()->route('dashboard'));

// ---- Protected routes — must be logged in ----
// 'no.viewer' blocks read-only (viewer) accounts from every write request.
Route::middleware(['auth', 'no.viewer'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Projects (المشاريع)
    Route::resource('projects', ProjectController::class);

    // Project bands (البنود) — nested under a project for create/store,
    // flat for edit/update/destroy since a band ID is already unique
    Route::get('/projects/{project}/bands/create', [ProjectBandController::class, 'create'])->name('projects.bands.create');
    Route::post('/projects/{project}/bands', [ProjectBandController::class, 'store'])->name('projects.bands.store');
    Route::get('/bands/{band}/edit', [ProjectBandController::class, 'edit'])->name('bands.edit');
    Route::put('/bands/{band}', [ProjectBandController::class, 'update'])->name('bands.update');
    Route::patch('/bands/{band}/status', [ProjectBandController::class, 'updateStatus'])->name('bands.updateStatus');
    Route::delete('/bands/{band}', [ProjectBandController::class, 'destroy'])->name('bands.destroy');

    // JSON endpoint used by materials/create.blade.php to refill the band dropdown
    Route::get('/api/projects/{project}/bands', [ProjectBandController::class, 'bandsJson'])->name('api.projects.bands');

    // Clients (العملاء)
    Route::resource('clients', ClientController::class)->except(['destroy']);

    // Transactions — read-only feed, auto-generated by model observers (see app/Observers)
    Route::get('/transactions', [TransactionController::class, 'index'])->name('transactions.index');

    // Materials (الخامات)
    Route::get('/materials', [MaterialController::class, 'index'])->name('materials.index');
    Route::get('/materials/create', [MaterialController::class, 'create'])->name('materials.create');
    Route::post('/materials', [MaterialController::class, 'store'])->name('materials.store');
    Route::delete('/materials/{material}', [MaterialController::class, 'destroy'])->name('materials.destroy');

    // Miscellaneous expenses (المصروفات النثرية) — tips/transport/meals, billed like materials
    Route::get('/projects/{project}/expenses/create', [MaterialController::class, 'createExpense'])->name('expenses.create');
    Route::post('/projects/{project}/expenses', [MaterialController::class, 'storeExpense'])->name('expenses.store');

    // Material returns (المرتجعات) — each return is tied to a specific purchase
    Route::get('/projects/{project}/returns/create', [MaterialReturnController::class, 'create'])->name('returns.create');
    Route::post('/projects/{project}/returns', [MaterialReturnController::class, 'store'])->name('returns.store');
    Route::delete('/returns/{return}', [MaterialReturnController::class, 'destroy'])->name('returns.destroy');

    // Installments — منظومة العقود والأقساط (عقود مربوطة بالمشاريع)
    Route::get('/installments', [InstallmentController::class, 'index'])->name('installments.index');
    Route::post('/installments', [InstallmentController::class, 'store'])->name('installments.store');
    // كشف حساب عميل (يُحمّل عند الطلب AJAX) — literal قبل أي {contract}
    Route::get('/installments/customer-statement', [InstallmentController::class, 'customerStatement'])->name('installments.customer_statement');
    // سداد دفعة (كامل/شهري/جزئي + خصم اختياري)
    Route::post('/installments/{contract}/pay', [InstallmentController::class, 'pay'])->name('installments.pay');
    // دفع جماعي للأقساط الشهرية لعدة عقود
    Route::post('/installments/pay-bulk', [InstallmentController::class, 'payBulk'])->name('installments.pay_bulk');
    // تعديل عقد
    Route::put('/installments/{contract}', [InstallmentController::class, 'update'])->name('installments.update');
    // (النظام القديم) تحديد قسط مشروع كمدفوع — يستخدمه المستحقات والتنبيهات
    Route::post('/installments/{installment}/mark-paid', [InstallmentController::class, 'markPaid'])->name('installments.markPaid');

    // Receivables — what clients owe us (المستحقات)
    Route::get('/receivables', [ReceivablesController::class, 'index'])->name('receivables.index');
    // تسجيل تحصيل مباشر من العميل (جزئي/كامل) + حذف تحصيل
    Route::post('/receivables/{project}/pay', [ReceivablesController::class, 'pay'])->name('receivables.pay');
    Route::delete('/receivables/payments/{transaction}', [ReceivablesController::class, 'deletePayment'])->name('receivables.payment.delete');

    // Supplier debts — what we owe suppliers (الديون)
    Route::get('/debts', [DebtController::class, 'index'])->name('debts.index');
    Route::post('/debts/{debt}/pay', [DebtController::class, 'pay'])->name('debts.pay');
    Route::post('/debts/supplier/{supplierId}/pay', [DebtController::class, 'paySupplier'])->name('debts.supplier.pay');
    Route::delete('/debts/{debt}', [DebtController::class, 'destroy'])->name('debts.destroy');

    // Suppliers (الموردون) — "compare" must be declared before the resource's {supplier} show route
    Route::get('/suppliers/compare', [SupplierController::class, 'compare'])->name('suppliers.compare');
    Route::resource('suppliers', SupplierController::class)->except(['destroy']);

    // Quotes (عروض الأسعار) — "approved" must be declared before the resource's {quote} show route
    Route::get('/quotes/approved', [QuoteController::class, 'approved'])->name('quotes.approved');
    Route::resource('quotes', QuoteController::class);
    Route::post('/quotes/{quote}/status', [QuoteController::class, 'updateStatus'])->name('quotes.status');
    // Converting an approved quote: a form first (which items were already bought?), then commit
    Route::get('/quotes/{quote}/convert', [QuoteController::class, 'convertForm'])->name('quotes.convert');
    Route::post('/quotes/{quote}/convert', [QuoteController::class, 'convertToProject'])->name('quotes.convert.store');

    // Labor (الفنيين والعمال) — flat work/wage log across all projects
    Route::get('/labor', [LaborController::class, 'index'])->name('labor.index');
    Route::get('/labor/create', [LaborController::class, 'create'])->name('labor.create');
    Route::post('/labor', [LaborController::class, 'store'])->name('labor.store');

    // Craftsman payments (دفعات الصنايعية) — each installment is paid as the
    // work progresses and hits the wallet the moment it's recorded
    Route::get('/workers/{worker}/payments', [WorkerPaymentController::class, 'show'])->name('workers.payments');
    Route::post('/workers/{worker}/payments', [WorkerPaymentController::class, 'store'])->name('workers.payments.store');
    // تبديل الفني — يثبّت الأول على المدفوع ويضيف فني جديد يكمّل الباقي
    Route::post('/workers/{worker}/swap', [WorkerPaymentController::class, 'swap'])->name('workers.swap');
    Route::delete('/worker-payments/{payment}', [WorkerPaymentController::class, 'destroy'])->name('worker-payments.destroy');

    // Unified craftsmen directory (الصنايعية ومستحقاتهم) — one person across all
    // their bands/projects, with what they're still owed
    Route::get('/craftsmen', [CraftsmanController::class, 'index'])->name('craftsmen.index');
    Route::post('/craftsmen/{name}/rate', [CraftsmanController::class, 'rate'])->name('craftsmen.rate');

    // Alerts / monitoring (التنبيهات)
    Route::get('/alerts', [AlertController::class, 'index'])->name('alerts.index');

    // Reports (التقارير): profitability table + printable client statement
    Route::get('/statement', [ReportController::class, 'statementIndex'])->name('reports.statement.index');
    Route::get('/reports/profitability', [ReportController::class, 'profitability'])->name('reports.profitability');
    Route::get('/reports/dashboard', [ReportController::class, 'dashboard'])->name('reports.dashboard');
    Route::get('/projects/{project}/statement', [ReportController::class, 'clientStatement'])->name('reports.statement');
    Route::get('/projects/{project}/statement/summary', [ReportController::class, 'clientStatementSummary'])->name('reports.statement.summary');

    // Analytics (التحليلات) + technicians labor report
    Route::get('/analytics', [AnalyticsController::class, 'index'])->name('analytics.index');
    Route::get('/analytics/technicians', [AnalyticsController::class, 'technicians'])->name('analytics.technicians');

    // Warranty tracking (متابعة الضمانات) — "create" must come before the {project}-bound show route
    Route::get('/warranties', [WarrantyController::class, 'index'])->name('warranties.index');
    Route::get('/warranties/create', [WarrantyController::class, 'create'])->name('warranties.create');
    Route::post('/warranties', [WarrantyController::class, 'store'])->name('warranties.store');
    Route::get('/warranties/{project}', [WarrantyController::class, 'show'])->name('warranties.show');
    Route::post('/warranties/{warranty}/complaints', [WarrantyController::class, 'storeComplaint'])->name('warranties.complaints.store');
    Route::post('/complaints/{complaint}/resolve', [WarrantyController::class, 'resolveComplaint'])->name('complaints.resolve');

    // Price history tracker (متابعة أسعار الخامات) — derived automatically from
    // sy2_materials, no manual entry. "index" before the {itemName} show route.
    Route::get('/price-history', [PriceHistoryController::class, 'index'])->name('price-history.index');
    Route::get('/price-history/{itemName}', [PriceHistoryController::class, 'show'])->name('price-history.show');

    // Admin-only area — settings + financial cost statements (real cost, profit)
    Route::middleware('role:admin')->group(function () {
        Route::get('/settings', [SettingsController::class, 'edit'])->name('settings.edit');
        Route::put('/settings', [SettingsController::class, 'update'])->name('settings.update');

        // محفظة المقاولات — balance + hand-entered money moves (capital in,
        // owner withdrawals, general overhead). Owner-level, hence admin-only.
        Route::get('/wallet', [WalletController::class, 'index'])->name('wallet.index');
        Route::post('/wallet/transactions', [WalletController::class, 'store'])->name('wallet.store');
        // Band statement (كشف حساب البند) — shows real cost & profit
        Route::get('/bands/{band}/statement', [ReportController::class, 'bandStatement'])->name('bands.statement');
        // Company cost statement (كشف حساب الشركة) — per-project real cost breakdown
        Route::get('/projects/{project}/company-statement', [ReportController::class, 'companyStatement'])->name('reports.company');

        // تقدير تكلفة مشروع جديد بالاعتماد على مشروع سابق كمرجع (خامات + مصنعية
        // بالتفصيل لكل بند) — "index" قبل الـ {project} الديناميكي
        Route::get('/reports/estimation', [ReportController::class, 'estimationIndex'])->name('reports.estimation.index');
        Route::get('/reports/estimation/{project}', [ReportController::class, 'estimationShow'])->name('reports.estimation.show');

        // تصفير قاعدة البيانات (للتجارب فقط) — يمسح كل بيانات المقاولات ويصفّر المحفظة
        Route::post('/maintenance/reset', [MaintenanceController::class, 'resetDatabase'])->name('maintenance.reset');

        // تعديل/حذف مركزي لأي حركة مالية — من سجل الحركات بس، محمي بباسورد الأدمن
        Route::put('/transactions/{transaction}', [TransactionController::class, 'update'])->name('transactions.update');
        Route::delete('/transactions/{transaction}', [TransactionController::class, 'destroy'])->name('transactions.destroy');
    });

    // Global search (بحث) — available from the topbar on every screen
    Route::get('/search', [SearchController::class, 'index'])->name('search.index');
});
