<?php

use App\Http\Controllers\AlertController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DebtController;
use App\Http\Controllers\InstallmentController;
use App\Http\Controllers\LaborController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\MaterialReturnController;
use App\Http\Controllers\PriceHistoryController;
use App\Http\Controllers\ProjectBandController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\QuoteController;
use App\Http\Controllers\ReceivablesController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\WarrantyController;
use Illuminate\Support\Facades\Route;

// ---- Auth routes (no login required) ----
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

// ---- Redirect root to dashboard ----
Route::get('/', fn () => redirect()->route('dashboard'));

// ---- Protected routes — must be logged in ----
// 'no.viewer' blocks read-only (viewer) accounts from every write request.
Route::middleware(['auth', 'no.viewer'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Projects (المشاريع)
    Route::resource('projects', ProjectController::class);

    // Project bands (البنود) — nested under a project for create/store,
    // flat for edit/update/destroy since a band ID is already unique
    Route::get('/projects/{project}/bands/create', [ProjectBandController::class, 'create'])->name('projects.bands.create');
    Route::post('/projects/{project}/bands', [ProjectBandController::class, 'store'])->name('projects.bands.store');
    Route::get('/bands/{band}/edit', [ProjectBandController::class, 'edit'])->name('bands.edit');
    Route::put('/bands/{band}', [ProjectBandController::class, 'update'])->name('bands.update');
    Route::patch('/bands/{band}/status', [ProjectBandController::class, 'updateStatus'])->name('bands.updateStatus');
    Route::delete('/bands/{band}', [ProjectBandController::class, 'destroy'])->name('bands.destroy');

    // JSON endpoint used by materials/create.blade.php to refill the band dropdown
    Route::get('/api/projects/{project}/bands', [ProjectBandController::class, 'bandsJson'])->name('api.projects.bands');

    // Clients (العملاء)
    Route::resource('clients', ClientController::class)->except(['destroy']);

    // Transactions — read-only feed, auto-generated by model observers (see app/Observers)
    Route::get('/transactions', [TransactionController::class, 'index'])->name('transactions.index');

    // Materials (الخامات)
    Route::get('/materials', [MaterialController::class, 'index'])->name('materials.index');
    Route::get('/materials/create', [MaterialController::class, 'create'])->name('materials.create');
    Route::post('/materials', [MaterialController::class, 'store'])->name('materials.store');
    Route::delete('/materials/{material}', [MaterialController::class, 'destroy'])->name('materials.destroy');

    // Miscellaneous expenses (المصروفات النثرية) — tips/transport/meals, billed like materials
    Route::get('/projects/{project}/expenses/create', [MaterialController::class, 'createExpense'])->name('expenses.create');
    Route::post('/projects/{project}/expenses', [MaterialController::class, 'storeExpense'])->name('expenses.store');

    // Material returns (المرتجعات) — each return is tied to a specific purchase
    Route::get('/projects/{project}/returns/create', [MaterialReturnController::class, 'create'])->name('returns.create');
    Route::post('/projects/{project}/returns', [MaterialReturnController::class, 'store'])->name('returns.store');
    Route::delete('/returns/{return}', [MaterialReturnController::class, 'destroy'])->name('returns.destroy');

    // Installments (الأقساط)
    Route::get('/installments', [InstallmentController::class, 'index'])->name('installments.index');
    Route::get('/installments/create', [InstallmentController::class, 'create'])->name('installments.create');
    Route::post('/installments', [InstallmentController::class, 'store'])->name('installments.store');
    Route::post('/installments/{installment}/paid', [InstallmentController::class, 'markPaid'])->name('installments.markPaid');
    Route::delete('/installments/{installment}', [InstallmentController::class, 'destroy'])->name('installments.destroy');
    // Installment plan generator (مولد خطة التقسيط)
    Route::get('/installments/plan', [InstallmentController::class, 'planForm'])->name('installments.plan.form');
    Route::post('/installments/plan', [InstallmentController::class, 'storePlan'])->name('installments.plan.store');
    // Printable installment statement per project (static /statement suffix — no conflict with /{installment})
    Route::get('/installments/{project}/statement', [InstallmentController::class, 'statement'])->name('installments.statement');
    // JSON: billed amount + paid installments for plan auto-fill
    Route::get('/api/projects/{project}/plan-data', [InstallmentController::class, 'planData'])->name('api.projects.plan-data');

    // Receivables — what clients owe us (المستحقات)
    Route::get('/receivables', [ReceivablesController::class, 'index'])->name('receivables.index');

    // Supplier debts — what we owe suppliers (الديون)
    Route::get('/debts', [DebtController::class, 'index'])->name('debts.index');
    Route::post('/debts/{debt}/pay', [DebtController::class, 'pay'])->name('debts.pay');
    Route::delete('/debts/{debt}', [DebtController::class, 'destroy'])->name('debts.destroy');

    // Suppliers (الموردون) — "compare" must be declared before the resource's {supplier} show route
    Route::get('/suppliers/compare', [SupplierController::class, 'compare'])->name('suppliers.compare');
    Route::resource('suppliers', SupplierController::class)->except(['destroy']);

    // Quotes (عروض الأسعار) — "approved" must be declared before the resource's {quote} show route
    Route::get('/quotes/approved', [QuoteController::class, 'approved'])->name('quotes.approved');
    Route::resource('quotes', QuoteController::class);
    Route::post('/quotes/{quote}/status', [QuoteController::class, 'updateStatus'])->name('quotes.status');
    // Converting an approved quote: a form first (which items were already bought?), then commit
    Route::get('/quotes/{quote}/convert', [QuoteController::class, 'convertForm'])->name('quotes.convert');
    Route::post('/quotes/{quote}/convert', [QuoteController::class, 'convertToProject'])->name('quotes.convert.store');

    // Labor (الفنيين والعمال) — flat work/wage log across all projects
    Route::get('/labor', [LaborController::class, 'index'])->name('labor.index');
    Route::get('/labor/create', [LaborController::class, 'create'])->name('labor.create');
    Route::post('/labor', [LaborController::class, 'store'])->name('labor.store');

    // Alerts / monitoring (التنبيهات)
    Route::get('/alerts', [AlertController::class, 'index'])->name('alerts.index');

    // Reports (التقارير): profitability table + printable client statement
    Route::get('/statement', [ReportController::class, 'statementIndex'])->name('reports.statement.index');
    Route::get('/reports/profitability', [ReportController::class, 'profitability'])->name('reports.profitability');
    Route::get('/reports/dashboard', [ReportController::class, 'dashboard'])->name('reports.dashboard');
    Route::get('/projects/{project}/statement', [ReportController::class, 'clientStatement'])->name('reports.statement');

    // Analytics (التحليلات) + technicians labor report
    Route::get('/analytics', [AnalyticsController::class, 'index'])->name('analytics.index');
    Route::get('/analytics/technicians', [AnalyticsController::class, 'technicians'])->name('analytics.technicians');

    // Warranty tracking (متابعة الضمانات) — "create" must come before the {project}-bound show route
    Route::get('/warranties', [WarrantyController::class, 'index'])->name('warranties.index');
    Route::get('/warranties/create', [WarrantyController::class, 'create'])->name('warranties.create');
    Route::post('/warranties', [WarrantyController::class, 'store'])->name('warranties.store');
    Route::get('/warranties/{project}', [WarrantyController::class, 'show'])->name('warranties.show');
    Route::post('/warranties/{warranty}/complaints', [WarrantyController::class, 'storeComplaint'])->name('warranties.complaints.store');
    Route::post('/complaints/{complaint}/resolve', [WarrantyController::class, 'resolveComplaint'])->name('complaints.resolve');

    // Price history tracker (متابعة أسعار الخامات) — derived automatically from
    // sy2_materials, no manual entry. "index" before the {itemName} show route.
    Route::get('/price-history', [PriceHistoryController::class, 'index'])->name('price-history.index');
    Route::get('/price-history/{itemName}', [PriceHistoryController::class, 'show'])->name('price-history.show');

    // Admin-only area — settings + financial cost statements (real cost, profit)
    Route::middleware('role:admin')->group(function () {
        Route::get('/settings', [SettingsController::class, 'edit'])->name('settings.edit');
        Route::put('/settings', [SettingsController::class, 'update'])->name('settings.update');
        // Band statement (كشف حساب البند) — shows real cost & profit
        Route::get('/bands/{band}/statement', [ReportController::class, 'bandStatement'])->name('bands.statement');
        // Company cost statement (كشف حساب الشركة) — per-project real cost breakdown
        Route::get('/projects/{project}/company-statement', [ReportController::class, 'companyStatement'])->name('reports.company');
    });

    // Global search (بحث) — available from the topbar on every screen
    Route::get('/search', [SearchController::class, 'index'])->name('search.index');
});
